// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbEk_1lDMvmMokbp7FVlA8BD1cApJb--M',
    appId: '1:87504596017:web:73188ea0c8f50574f1f910',
    messagingSenderId: '87504596017',
    projectId: 'bukizz1',
    authDomain: 'bukizz1.firebaseapp.com',
    databaseURL: 'https://bukizz1-default-rtdb.firebaseio.com',
    storageBucket: 'bukizz1.appspot.com',
    measurementId: 'G-Z4ZB84DTZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmx20-mEPRqrJqA-CeTB55DHGQgW0Eswo',
    appId: '1:87504596017:android:c4a30f30f8b7f9e3f1f910',
    messagingSenderId: '87504596017',
    projectId: 'bukizz1',
    databaseURL: 'https://bukizz1-default-rtdb.firebaseio.com',
    storageBucket: 'bukizz1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkMZGo9aX68TOuMhqrppk1Kq9Qv3Cbxxs',
    appId: '1:87504596017:ios:bbf3580c36f447b8f1f910',
    messagingSenderId: '87504596017',
    projectId: 'bukizz1',
    databaseURL: 'https://bukizz1-default-rtdb.firebaseio.com',
    storageBucket: 'bukizz1.appspot.com',
    androidClientId: '87504596017-2oov149952gg2k3purvepf7nfk84niil.apps.googleusercontent.com',
    iosClientId: '87504596017-ubc7f81fuel2mij1oi8q1koct9c6b14u.apps.googleusercontent.com',
    iosBundleId: 'com.bukizz.bukizzdelivery.bukizzDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkMZGo9aX68TOuMhqrppk1Kq9Qv3Cbxxs',
    appId: '1:87504596017:ios:5866f8a25bf9124ef1f910',
    messagingSenderId: '87504596017',
    projectId: 'bukizz1',
    databaseURL: 'https://bukizz1-default-rtdb.firebaseio.com',
    storageBucket: 'bukizz1.appspot.com',
    androidClientId: '87504596017-2oov149952gg2k3purvepf7nfk84niil.apps.googleusercontent.com',
    iosClientId: '87504596017-7kd99o3701vmal7aemils6rt085ho883.apps.googleusercontent.com',
    iosBundleId: 'com.bukizz.bukizzdelivery.bukizzDelivery.RunnerTests',
  );
}
